### ISSUE TITLE
Error de link en pagina Sobre Mí

### ISSUE THREAD

**Issue by daniel-olmos** [FiliSantillan/filisantillan.com#22]
Link: https://filisantillan.com/sobre-mi/

el ingresar a la pagina indicada, cuando deseo ver tu stack, este me re-direcciona a Localhost

![image](https://user-images.githubusercontent.com/13950641/81821979-eefc2380-9508-11ea-81f2-993de74cc092.png)

re-dirección:

![image](https://user-images.githubusercontent.com/13950641/81822048-02a78a00-9509-11ea-8ca4-108394ba3942.png)

**Comment by FiliSantillan** [comment]
Hola @daniel-olmos , muchas gracias por la notificación. Ya aplique la corrección 👍.

**Comment by daniel-olmos** [comment]
Hola @FiliSantillan, Genial!!, Muchos éxitos
